<!-- Adding a header file which will be included in every page -->
<header>
  <div class="container">
    <div id="site_name"> 
      <h1><span class="highlight">ParkingSpot</span> Locator</h1>
    </div>
    <nav>
      <ul>
        <li><a href="register.php">Home</a></li>
        <li><a href="login.php">Sign in</a></li>
        <li><a href="">Sign out</a></li>
        <li><a href="submission.php">Submit</a></li>
      </ul>
    </nav>
  </div>
</header>